### PR TITLE
Hello microverse devlopment

### PR DESCRIPTION
**Pull request by melkamu372**
Hello microverse devlopment

### CODE REVIEW

**Review by skyv26 — CHANGES_REQUESTED** [review]
## Hi @melkamu372, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## STATUS: REQUIRE CHANGES 🔴 



## Highlights
- Correct `GitHub` flow ✅ 
- Linters are green ✅ 

## Required Changes ♻️

- [ ] Please try to write a descriptive PR as I can see that your PR description is empty which is not professional at all, having a descriptive PR will help any person to understand your project feature implementation detail.

<table>
<tr>
<th align=“middle”>Your PR description</th>
<th align=“middle”>Professional PR description</th>
</tr>
<tr>
<td>

Screenshot from 2023-05-31 00-29-37

</td>
<td>

Screenshot from 2023-04-28 21-07-13

</td>
</tr>
</table>
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag @skyv26 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by melkamu372** [comment]
Hello @skyv26 Thank you for feed back I try to make the PR as your suggestion can you review it now

**Comment by skyv26** [comment]
@melkamu372 why you merged your branch without getting approval? I just gave you the changes that you suppose to be made it here and submit this same link for project review. Please make sure that you must have to use only one PR until not getting the approval from code reviewer.

**Comment by skyv26** [comment]
@melkamu372 Please take care next time and submit your project with new PR link and in the description please mention this PR link so that a code reviewer can understand the situation correctly.

**Comment by melkamu372** [comment]
@skyv26  shall I go to dashboard and request  re review?

**Comment by skyv26** [comment]
@melkamu372 Yes please 🚀

**Comment by melkamu372** [comment]
@skyv26 there is no way to re request it only have view submission

**Comment by skyv26** [comment]
@melkamu372 please ask for help from someone

**Pull request merged**
